[package]
name = "somehal"
version.workspace = true
edition.workspace = true

[features]
vm = []
early-debug = []

[dependencies]
somehal-macros = { path = "../somehal-macros" }
kmem = { path = "../kmem" }
spin = "0.10.0"
link-boot = { version = "0.2" }
tock-registers = "0.9"
log = "0.4"
bitflags = "2.9"

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
page-table-arm = "0.1"
smccc = "0.2"
arm-gic-driver = "0.7"
any-uart = "0.2"
fdt-parser = "0.4"
