[package]
name = "somehal"
version.workspace = true
edition.workspace = true

[features]
vm = []


[dependencies]
somehal-macros = { path = "../somehal-macros" }
kmem = { path = "../kmem" }
spin = "0.10.0"
arrayvec = { version = "0.7", default-features = false }
link-boot = {version =  "0.2", path = "/home/zhourui/opensource/link_boot"}

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
page-table-arm = "0.1"
smccc = "0.2"
arm-gic-driver = "0.7"
any-uart = "0.2"
