[package]
name = "kmem"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2.9"
link-boot = { version = "0.2" }