[package]
name = "num-align"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
categories.workspace = true
description.workspace = true
keywords = ["num", "align"]
license.workspace = true
repository.workspace = true



[dependencies]
